import type { SiteSettings } from "@/lib/site-settings.types";

export const defaultSiteSettings: SiteSettings = {
  site: {
    name: "GameZone",
    tagline: "Free Online Games",
    description:
      "Play free online games — puzzle, arcade, hypercasual, and more on GameZone.",
    copyrightYear: 2026,
  },
  ads: {
    gptNetworkCode: "",
    gptPublisherId: "",
    adsTxt: "",
    globalHeadScripts: "",
    globalBodyScripts: "",
    headerBanner: {
      enabled: true,
      provider: "gpt",
      slotId: "demo-ad-container",
      label: "Header Banner",
      gptUnitPath: "/6355419/Travel/Europe/France/Paris",
      sizes: [[300, 250]],
      adsenseClient: "",
      adsenseSlot: "",
      customHtml: "",
    },
    bottomAnchor: {
      enabled: true,
      provider: "gpt",
      slotId: "bottom-anchor-ad",
      label: "Bottom Sticky Banner",
      gptUnitPath: "/6355419/Travel/Europe",
      sizes: [
        [320, 50],
        [728, 90],
      ],
      mobileSizes: [[320, 50]],
      desktopSizes: [[728, 90]],
      adsenseClient: "",
      adsenseSlot: "",
      customHtml: "",
    },
    gameInterstitial: {
      enabled: true,
      provider: "gpt",
      slotId: "game-interstitial-ad",
      label: "Pre-Play Interstitial (on Play Now)",
      gptUnitPath: "/6355419/Travel/Europe/France/Paris",
      sizes: [
        [300, 250],
        [320, 480],
        [336, 280],
      ],
      adsenseClient: "",
      adsenseSlot: "",
      customHtml: "",
    },
    detailBanner1: {
      enabled: false,
      provider: "disabled",
      slotId: "div-gpt-ad-detail-banner-01",
      label: "Game Detail Banner 1",
      gptUnitPath: "",
      sizes: [[300, 250]],
      adsenseClient: "",
      adsenseSlot: "",
      customHtml: "",
    },
    detailBanner2: {
      enabled: false,
      provider: "disabled",
      slotId: "div-gpt-ad-detail-banner-02",
      label: "Game Detail Banner 2",
      gptUnitPath: "",
      sizes: [[300, 250]],
      adsenseClient: "",
      adsenseSlot: "",
      customHtml: "",
    },
  },
  homepage: {
    heroGameId: "29221",
  },
  updatedAt: "2026-06-12T00:00:00.000Z",
};
